### ISSUE TITLE
Кастомные маркеры на карте

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-elementor-yandex-maps#1]
- https://tech.yandex.ru/maps/jsapi/doc/2.1/dg/concepts/geoobjects-docpage/#geoobjects__icon-style
- https://tech.yandex.ru/maps/jsbox/2.1/icon_customImage

**Comment by dbelyaeff** [comment]
Доброго времени суток!

Как прогресс по данному улучшению?

**Comment by mihdan** [comment]
@codemotion сделали
