### ISSUE TITLE
Подтягивать метки из CPT

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-elementor-yandex-maps#12]
Просил Олег из ТГ @olegneoleg
Просил Виталий на [форуме](https://wordpress.org/support/topic/%d0%bf%d0%bb%d0%b0%d0%b3%d0%b8%d0%bd-%d0%be%d1%87%d0%b5%d0%bd%d1%8c-%d0%bf%d0%be%d0%bd%d1%80%d0%b0%d0%b2%d0%b8%d0%bb%d1%81%d1%8f-%d0%b6%d0%b4%d0%b5%d0%bc-%d0%bf%d0%be%d0%b4%d0%b4%d0%b5%d1%80%d0%b6/) 
Просил Андрей в [блоге](https://www.kobzarev.com/projects/mihdan-elementor-yandex-maps/#comment-48487)

**Comment by Olegggggggg** [comment]
+

**Comment by stasonua0** [comment]
+1
