### ISSUE TITLE
Динамически данные для карты

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-elementor-yandex-maps#2]
Как это реализовано в плагине под Google 

![](http://screenshot.kobzarev.com/2019-04-17-1555496084.png)

**Comment by yelow59** [comment]
Это будет самым полезным допом

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-elementor-yandex-maps/commit/cacc4bd6429dbb594060794f23afc9e3b31607b9
