### ISSUE TITLE
Показать карточку объекта на карте рядом с маркером

### ISSUE THREAD

**Issue by Marat78** [mihdan/mihdan-elementor-yandex-maps#3]
Желательно бы реализовать возможность показа карточки объекта на карте рядом с маркером. Или хотя бы адрес объекта.

Спасибо!

**Comment by yelow59** [comment]
Тоже полезная фича

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-elementor-yandex-maps/commit/6cd74d2cb102f275dd34fe1d823528061bffa666
