### ISSUE TITLE
Добавить поддержку всех брейкпоинтов в Elementor

### ISSUE THREAD

**Issue by zaostr** [mihdan/mihdan-elementor-yandex-maps#30]
В блочном редакторе Elementor есть возможность добавить дополнительные брейкпоинты.
А в плагине используются только дефолтные (Desktop, Tablet Portrait, Mobile Portrait).
Насколько я понимаю, из-за этого ловлю ошибку в консоли, карта не грузится, когда страница загружается на каком либо из дополнительных брейпоинтов.
Список брейкпоинтов:
- Mobile Portrait
- Mobile Landscape
- Tablet Portrait
- Tablet Landscape
- Laptop
- Widescreen

Также прикладываю скрины
![Снимок экрана 2023-05-04 011737](https://user-images.githubusercontent.com/86747063/236062732-2c2ee7b3-a43a-4fa1-931c-f1a7dbfeb9ae.jpg)
![Снимок экрана 2023-05-04 011856](https://user-images.githubusercontent.com/86747063/236062753-6d7d3fae-ec30-4326-a5a1-861bbc7e5eac.jpg)
![Снимок экрана 2023-05-04 012249](https://user-images.githubusercontent.com/86747063/236062792-6b0f7bab-859f-41d3-854f-090a3651ab5e.jpg)

**Comment by mihdan** [comment]
Реализовано в версии 1.6.4
